### ISSUE TITLE
Console App for NEAR BC

### ISSUE THREAD

**Issue by antonpegov** [zeropoolnetwork/zeropool-console#3]
**As a User**
**I want to** navigate to console app
**so that** I could use it commands for NEAR BC

### **Acceptance Criteria**:

**Given** I accessing Console App
**When** I enter console commands 
**Then** 
- [ ] I can _replace the seed phrase for the current account_
- [ ] I can _print the seed phrase for the current account_
- [ ] I can _generate and print a new seed phrase_
- [ ] I can _derive and print a new address with specified coin_type_
- [ ] I can _print an address for the current NEAR account_
- [ ] I can _print the private key for the current NEAR account_
- [ ] I can _fetch and print account balance_
- [ ] I can _unlock the current account if was locked by a timeout_
- [ ] I can _transfer near tokens_
- [ ] I can _clear terminal window_
- [ ] I can _reset console state_
- [ ] I can _print help message_
